-- AlterTable
ALTER TABLE "Individualist" ADD COLUMN     "qd" DOUBLE PRECISION,
ADD COLUMN     "qe" DOUBLE PRECISION,
ADD COLUMN     "qn" DOUBLE PRECISION,
ADD COLUMN     "qp" DOUBLE PRECISION,
ADD COLUMN     "qsc" DOUBLE PRECISION,
ADD COLUMN     "qsi" DOUBLE PRECISION,
ADD COLUMN     "rawComponents" JSONB NOT NULL DEFAULT '{}';

-- AlterTable
ALTER TABLE "MathTeam" ADD COLUMN     "historicalResults" JSONB NOT NULL DEFAULT '{}';
